# Testing GKE Secret Manager CSI from https://cloud.google.com/secret-manager/docs/secret-manager-managed-csi-component
apiVersion: v1
kind: Namespace
metadata:
  name: test-secrets
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gcloud-ksa
  namespace: test-secrets
---
# Specify which secrets should be used
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: my-secrets
  namespace: test-secrets
spec:
  provider: gke
  parameters:
    secrets: |
      - resourceName: "projects/503076227230/secrets/test-secret/versions/latest"
        path: "test-secret.txt"
#      - resourceName: "projects/503076227230/secrets/another/versions/latest"
#        path: "another.txt"
# Make sure KSA has permissions to all secrets https://cloud.google.com/secret-manager/docs/secret-manager-managed-csi-component#use-existing-service-account
# Otherwise you will see pod stuck in ContainerCreating with event description like:
#   MountVolume.SetUp failed for volume "mysecret" : rpc error: code = Internal desc = failed to mount secrets store objects for pod test-secrets/gcloud-bare-pod,
#   err: rpc error: code = Internal desc = rpc error: code = PermissionDenied desc = Permission 'secretmanager.versions.access' denied for resource 'projects/503076227230/secrets/another/versions/1' (or it may not exist).
---
apiVersion: v1
kind: Pod
metadata:
  name: gcloud-bare-pod
  namespace: test-secrets
spec:
  terminationGracePeriodSeconds: 0
  serviceAccountName: gcloud-ksa
  containers:
  - image: google/cloud-sdk:slim
    name: gcloud
    command: ["sleep","infinity"]
    volumeMounts:
      - mountPath: "/var/secrets"
        name: secrets
  volumes:
  # configure where secrets are mounted https://cloud.google.com/secret-manager/docs/secret-manager-managed-csi-component#create-volume
  - name: secrets
    csi:
      driver: secrets-store-gke.csi.k8s.io
      readOnly: true
      volumeAttributes:
        secretProviderClass: my-secrets
