apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: metadata-google-internal
  namespace: istio-system
spec:
  hosts:
  - metadata.google.internal
  addresses:
  - 169.254.169.254/32
  exportTo:
  - "*"   # All Namespaces
  location: MESH_EXTERNAL
  ports:
  - name: http
    number: 80
    protocol: HTTP
  resolution: NONE
