# Kubernetes Secrets in GKE Sandbox https://kubernetes.io/docs/concepts/configuration/secret/
apiVersion: v1
kind: Secret
metadata:
  name: k8s-secret
  namespace: test-sandbox
data:
  .secret-file: aHVudGVyMg==  # echo -n "hunter2" | base64
---
apiVersion: agents.x-k8s.io/v1alpha1
kind: Sandbox
metadata:
  name: agentsandbox-k8s-secrets
  namespace: test-sandbox
spec:
  podTemplate:
    metadata:
      labels:
        sandbox: my-sandbox
    spec:
      runtimeClassName: gvisor            # Required
      automountServiceAccountToken: false # Required
      securityContext:
        runAsNonRoot: true                # Required
        runAsUser: 1000                   # Required if image defaults to root (e.g. busybox)
        runAsGroup: 1000
      nodeSelector:
        sandbox.gke.io/runtime: gvisor    # Required
      tolerations:
      - key: "sandbox.gke.io/runtime"
        value: "gvisor"
        effect: "NoSchedule"              # Required
      serviceAccountName: default
      containers:
      - name: my-container
        image: busybox
        command: ["/bin/sh", "-c", "sleep infinity"]
        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"     # Required
        securityContext:
          capabilities:
            drop: ["ALL"]     # Required
          allowPrivilegeEscalation: false
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        volumeMounts:
        - name: secret-volume
          readOnly: true
          mountPath: "/var/secrets/test"
      volumes:
      - name: secret-volume
        secret:
          secretName: k8s-secret

# kubectl exec -it -n test-sandbox agentsandbox-k8s-secrets -- /bin/sh -c 'grep -H ^ /var/secrets/test/.secret*'
#/var/secrets/test/.secret-file:hunter2

# If the Kubernetes secret is updated the file in the volume will also be updated. 
# Just watch out for trailing newlines if you are expecting single string/word values.
