# Secret Manager CSI volume inside GKE Agent Sandbox. See other setup requirements from https://github.com/gbrayut/cloud-examples/blob/main/gke-iam-misc/secrets.md
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gcloud-ksa
  namespace: test-sandbox
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: my-secrets
  namespace: test-sandbox
spec:
  provider: gke
  parameters:
    secrets: |
      - resourceName: "projects/503076227230/secrets/test-secret/versions/latest"   # Must change this to match your Project Number and Secret Name
        path: "test-secret.txt"
---
# Test pod without sandbox first
apiVersion: v1
kind: Pod
metadata:
  name: secrets-nosandbox
  namespace: test-sandbox
spec:
  terminationGracePeriodSeconds: 0
  serviceAccountName: gcloud-ksa
  containers:
  - image: google/cloud-sdk:slim
    name: gcloud
    command: ["sleep","infinity"]
    volumeMounts:
      - mountPath: "/var/secrets"
        name: secrets
  volumes:
  # configure where secrets are mounted https://cloud.google.com/secret-manager/docs/secret-manager-managed-csi-component#create-volume
  - name: secrets
    csi:
      driver: secrets-store-gke.csi.k8s.io
      readOnly: true
      volumeAttributes:
        secretProviderClass: my-secrets
---
# Test sandbox pod
apiVersion: agents.x-k8s.io/v1alpha1
kind: Sandbox
metadata:
  name: agentsandbox-secret-manager
  namespace: test-sandbox
spec:
  podTemplate:
    metadata:
      labels:
        sandbox: my-sandbox
    spec:
      runtimeClassName: gvisor            # Required
      automountServiceAccountToken: false # Required
      securityContext:
        runAsNonRoot: true                # Required
        runAsUser: 1000                   # Required if image defaults to root (e.g. busybox)
        runAsGroup: 1000
      nodeSelector:
        sandbox.gke.io/runtime: gvisor    # Required
      tolerations:
      - key: "sandbox.gke.io/runtime"
        value: "gvisor"
        effect: "NoSchedule"              # Required
      serviceAccountName: gloud-ksa
      containers:
      - name: my-container
        image: busybox
        command: ["/bin/sh", "-c", "sleep infinity"]
        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"     # Required
        securityContext:
          capabilities:
            drop: ["ALL"]     # Required
          allowPrivilegeEscalation: false
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        volumeMounts:
        - mountPath: "/var/secrets"
          name: secrets
      volumes:
      # configure where secrets are mounted https://cloud.google.com/secret-manager/docs/secret-manager-managed-csi-component#create-volume
      - name: secrets
        csi:
          driver: secrets-store-gke.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: my-secrets

# kubectl exec -it -n test-sandbox secrets-nosandbox -- /bin/bash -c 'grep -H ^ /var/secrets/*'
# kubectl exec -it -n test-sandbox agentsandbox-secrets -- /bin/sh -c 'grep -H ^ /var/secrets/*'
#
# Both should show something like:
# /var/secrets/test-secret.txt:hunter2
#
# Also note that projected secret values are only refreshed when a pod is created unless you are
# using automatic rotation https://docs.cloud.google.com/secret-manager/docs/secret-manager-managed-csi-component#configure-auto-rotation

# Test pods getting new values by updating the secret using something like:
# gcloud secrets versions add test-secret --data-file=<(echo -n hunter3)
