apiVersion: v1
kind: PodTemplate
metadata:
  name: dws-pr-template
  namespace: default
  labels:
    cloud.google.com/apply-warden-policies: "true"
# The template is used by GKE scheduler to figure out how many nodes are needed.
# It does NOT generate actual pods!
template:
  metadata:
    labels:
      app: dwspod
  spec:
    nodeSelector:
      cloud.google.com/gke-nodepool: dws-h100  # Must match the name of your DWS nodepool
    tolerations:
      - key: "nvidia.com/gpu"
        operator: "Exists"
        effect: "NoSchedule"
    containers:
      - name: pi
        image: perl
        command: ["/bin/sh"]
        resources:
          limits:
            cpu: "700m"
            nvidia.com/gpu: "8" # Make sure these both match expected GPU per Pod so scheduler will request correct node count
          requests:
            cpu: "700m"
            nvidia.com/gpu: "8"
    restartPolicy: Never
---
apiVersion: autoscaling.x-k8s.io/v1
kind: ProvisioningRequest
metadata:
  name: dws-1hr-pr    # usually a unique name including a timestamp (example: ml-job-20250308-140100)
  namespace: default
spec:
  provisioningClassName: queued-provisioning.gke.io
  parameters:
    maxRunDurationSeconds: "3600"
  podSets:
  - count: 2          # combined with container resource requests above to determine size of node pool (two a3-highgpu-8g in this case)
    podTemplateRef:
      name: dws-pr-template

# kubectl describe provisioningrequest dws-1hr-pr
# should take ~5 minutes for two a3-highgpu-8g
# NOTE: if the nodes don't have a GPU workload applied (see below) shortly after they are ready,
# the cluster autoscaler could flag it for downscaling. DWS also will expire the ProvisioningRequest
# capacity eary if the original workload is removed:
#
#  Message:  Capacity booking for the Provisioning Request has expired and the nodes are now candidates for scale down when underutilized.
#  Reason:   BookingExpired
# 
#   Warning  IgnoredInScaleUp  2m11s  cluster-autoscaler    Unschedulable pod ignored in scale-up loop, 
#   because it's consuming ProvisioningRequest default/dws-1hr-pr that is in BookingExpired state. 
#   The pod most likely arrived too late and will never schedule as the VM was already scaled-down.
