apiVersion: v1
kind: ServiceAccount
metadata:
  name: testing-service-account
  namespace: testing
  annotations:
    iam.gke.io/gcp-service-account: "test-sa@gregbray-vpc.iam.gserviceaccount.com"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcloud
  namespace: testing
  labels:
    app: gcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gcloud
  template:
    metadata:
      labels:
        app: gcloud
    spec:
      serviceAccountName: testing-service-account
      nodeSelector:
        iam.gke.io/gke-metadata-server-enabled: "true"
      containers:
      - name: gcloud
        image: google/cloud-sdk:slim
        command: ["sleep","infinity"]
# Check metadata server using:
# kubectl exec -it deploy/gcloud --namespace testing -- curl -H "Metadata-Flavor: Google" http://169.254.169.254/computeMetadata/v1/instance/service-accounts/
# kubectl exec -it deploy/gcloud --namespace testing -- curl -H "Metadata-Flavor: Google" http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/test-sa@gregbray-vpc.iam.gserviceaccount.com/token
# or via gcloud using:
# kubectl exec -it deploy/gcloud --namespace testing -- gcloud auth application-default print-access-token
