apiVersion: v1
kind: Namespace
metadata:
  labels:
    istio.io/rev: default
  name: app-2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whereami
  namespace: app-2
  labels:
    app: whereami
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whereami
  template:
    metadata:
      labels:
        app: whereami
    spec:
      containers:
      # https://github.com/GoogleCloudPlatform/kubernetes-engine-samples/tree/main/whereami
      - name: whereami
        image: us-docker.pkg.dev/google-samples/containers/gke/whereami:v1.2.19
        ports:
        - containerPort: 8080
        env:
        - name: NODE_NAME #The node name the pod is running on
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAMESPACE #The kubernetes Namespace where the Pod is running
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP #The IP address of the pod
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: ECHO_HEADERS
          value: "True"
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "whereami"
  namespace: app-2
spec:
  # See https://istio.io/latest/docs/ops/configuration/traffic-management/protocol-selection/
  ports:
  - port: 80
    targetPort: 8080
    appProtocol: http
    name: http
  selector:
    app: "whereami"
  type: "ClusterIP"
---
# https://cloud.google.com/service-mesh/docs/security/configuring-mtls
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: app-2
  namespace: app-2
spec:
  # Use selector to apply to specific workloads
  selector:
    matchLabels:
      app: whereami
  mtls:
    # https://istio.io/latest/docs/reference/config/security/peer_authentication/#PeerAuthentication-MutualTLS-Mode
    mode: UNSET   # Inherits value from namespace or uses PERMISSIVE by default
  portLevelMtls:
    # Require mTLS for specific container ports
    8080:
      mode: STRICT
    # Disable mTLS for any container ports that are bypassing envoy sidecar
    #8081:
    #  mode: DISABLE
